<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

Each array method is to allow different way of handling data. Each got its own features

In [2]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]
#python array

In [3]:
import numpy as np
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])
#numpy array

In [4]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}
#dictionary

## 1.2 Accessing data from a list (or array)

![](https://sps.nus.edu.sg/sp2273/docs/python_basics/03_storing-data/python-zero-indexed-counting.png)

In [8]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

#Py runs on 0 indices, meaning if I want second element, it will be at pos. 2

py_real_names[0]
py_super_names[1] #access the second element

'Iron Man'

In [1]:
import numpy as np
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

np_super_names[0] = 'Yippe' #you can do this if you want.
np_super_names[0]

np.str_('Yippe')

In [3]:
py_super_names[-1] #go reverse order, for -1 it gives you the last element. -2 for last second element

'Doctor Strange'

In [5]:
superhero_info['Peter Parker']= 'Spider Man' #inserting spiderman into the array
superhero_info

{'Natasha Romanoff': 'Black Widow',
 'Tony Stark': 'Iron Man',
 'Stephen Strange': 'Doctor Strange',
 'Peter Parker': 'Spider Man'}

## 1.3 Accessing data from a dictionary

In [6]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange', 'Peter Parker'])

In [7]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange', 'Spider Man'])

## 1.4 Higher dimensional lists

In [8]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]
#storing list in a list, recommended to use a dictionary

# 2 Lists vs. Arrays

## 2.1 Size

In [9]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d) #converting py list to convert into numpy arrays    

In [11]:
np_array_2d #you get the same data, but its in an array
#telling it to store in this data type '<U21'

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C'],
       ['4', 'D'],
       ['5', 'E'],
       ['6', 'F'],
       ['7', 'G'],
       ['8', 'H'],
       ['9', 'I'],
       ['10', 'J']], dtype='<U21')

In [13]:
len(py_list_2d) #gives you the first dimension only. Think of it as 2D, having 10 rows and 2 cols. 
#len always give no. of rows
len(np_array_2d) 
np_array_2d.shape #.shape gives you rows, cols.

(10, 2)

In [23]:
'Hahahaha'.upper() #when you use (), it runs like instructions
np_array_2d.shape #.shape is an attribute, and is it generated when using array

'HAHAHAHA'

In [22]:
np_array_2d.shape #tells you dimension
#numpy takes chunk of memory and does it in a way it can process information in all rows and cols.
#not uniform number of rows or cols in certain elements gives numpy error

(10, 2)

In [21]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J", "hahahah"]]
py_list_2d #more flexible, allow you to add in str, int etc.

[[1, 'A'],
 [2, 'B'],
 [3, 'C'],
 [4, 'D'],
 [5, 'E'],
 [6, 'F'],
 [7, 'G'],
 [8, 'H'],
 [9, 'I'],
 [10, 'J', 'hahahah']]

## 2.2 Arrays are fussy about type

In [14]:
py_list = [1, 1.5, 'A']
py_list #Runs fine, does not complain

[1, 1.5, 'A']

In [15]:
np_array = np.array(py_list)
np_array #when convert to array, it tell you to convert to <U32 as its optimised.
#speed, forces you to convert it to a single type
#all numpy array must have same type.

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [17]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [18]:
np_array + 10 #useful for changing a lot of data very fast


array([11, 12, 13, 14, 15])

In [21]:
py_list + 10 #adding a list and a number, will have error

py_list +[10] #need to add [], list have append function that is faster than this

TypeError: can only concatenate list (not "int") to list

## 2.4 Adding another list

In [22]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [25]:
py_list_1 + py_list_2 #adding lists cause them to grow

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [24]:
np_array_1 + np_array_2 #adding arrays is element-wise operation

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [27]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [32]:
py_list*2 #replicates the list

[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]

In [30]:
np_array*2 #multiply its elements by the no.

array([ 2,  4,  6,  8, 10])

In [43]:
np_array * 10 #useful for changing a lot of data very fast

py_list * [10] #Doesn't work

TypeError: can't multiply sequence by non-int of type 'list'

## 2.6 Squaring

In [48]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [50]:
#Arrays
np_array ** 2 #element wise operation

array([ 1,  4,  9, 16, 25])

In [51]:
py_list**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [47]:
#List
[1, 2] * 10 #doesn't work
[1, 2] ** 2 #Doesn't work

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

## 2.7 Asking questions

In [65]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [68]:
py_list == 3 # asking if your list is 3. Wont complain, becareful when using
#when to comes to math operation, use array

False

In [66]:
np_array == 3  #asking whether are you 3, goes element wise

array([False, False,  True, False, False])

In [67]:
np_array > 3   #asking whether you are >3 element wise

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [60]:
sum(py_list)     # sum() is a base Python function
max(py_list)     # max() is a base Python function
min(py_list)     # min() is a base Python function
#green are base python functions

1

In [61]:
np_array.sum()
np_array.max()
np_array.min()
np_array.mean()
np_array.std()
#jupyter only shows the last result
#hidden function method, a lot of fancy hidden functions
#cannot mix

np.float64(1.4142135623730951)

In [62]:
print(np_array.sum())
print(np_array.max())
print(np_array.min())
print(np_array.mean())
print(np_array.std())
#add print if you want to see individual results

15
5
1
3.0
1.4142135623730951


In [64]:
%%timeit
sum(np_array) #python sym function on a numpy list

1.1 μs ± 11.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [65]:
%%timeit
np_array.sum() #using numpy function
#numpy generally should be faster. It appears slower cuz small data set

1.86 μs ± 8.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


## Footnotes

### Arrays

In [1]:
py_list = [[1, 1], [2, 1], [3, 1], [4, 1], [5, 1]]

In [68]:
sum(py_list)

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [7]:
import numpy as np
np_array = np.array(py_list) #converting py_list to array

In [6]:
np_array.sum() #stripped it off its 2D-ness. By default give you the whole list

np.int64(20)

In [ ]:
#If want sum of rows or cols etc., numpy.sum() has default settings

In [8]:
np_array.sum(axis=1) #adding elements within each []

array([2, 3, 4, 5, 6])