<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

In [2]:
import numpy as np #Every notebook has its own kernel

# What to expect in this chapter

# 1 Subsetting (A few items): Indexing (Taking 1) and Slicing (Taking whole chunk)
Take data and chop it up into pieces 

In [5]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
#x = np_array

In [17]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

#
x = py_list
x
x[3] #extract 3rd element
x[2:5] #only liss element 2 and 4
# always get difference in that many elements. always get  5 minus 2
x[2:] #starts at index 2, list all the way
x[2::2] #starts from index 2, intervals of 2 indexes
x[2:8:2] #starts index 2, 6 elements, go in intervals of 2 index
x[::-1] #starts listing from the back to front

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

## 1.2 Arrays only | Subsetting by masking

In [24]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3 #asking what numbers are > 3
my_mask 
#Have to pick a set of numbers based on condition aka masking.

np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = (np_array > 3) & (np_array < 8)  #asking what numbers are > 3 & <8. cannot use 'and' as its a python function
my_mask #only tells you t f
np_array[my_mask] #only tells you which element is true


array([4, 5, 6, 7])

In [25]:
my_mask.sum() #false = 0 and t = 1. When sum them, it tells you how many trues

np.int64(4)

In [26]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = (np_array > 3) & (np_array < 8)  #have to use brackets
my_mask
np_array[~my_mask] #only tells you which element is not true
#addition '~' negative selects

array([ 1,  2,  3,  8,  9, 10])

In [31]:
#Asking for >3 or < 8
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = (np_array > 3) | (np_array < 8)  #have to use brackets
np_array[my_mask]
#addition '|' denotes as or

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [32]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [41]:
py_list_2d[3]
py_list_2d[3,1] # if i want to get D, it doesn't work for array
py_list_2d[3][1] #it will work

TypeError: list indices must be integers or slices, not tuple

In [35]:
np_array_2d[3]
np_array_2d[3,1] #Directly gets you where you want to go

np.str_('D')

In [ ]:
x=[][] #see on phone

## 1.4 Growing lists

# Some loose ends

## 1.5 Tuples

## 1.6 Be VERY careful when copying

## Footnotes